# Let NetworkManager manage all devices on this system
network:
        ethernets:
                eno1:
                        dhcp4: false
                        optional: true

        bridges:
                br0:
                        interfaces: [eno1]
                        dhcp4: false
                        addresses: [192.168.2.100/24]
                        gateway4: 192.168.2.2
                        optional: true                                          
                        nameservers:                                            
                                addresses: [192.168.2.2,8.8.8.8]                
                                                                                
        version: 2
